apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-v7zy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0075-tenant/tkrw-pr712-0075-0075-app/devfile-sample-v7zy@sha256:8ef51cee198a54a7f13cd09f32ea3afb91f7256afe7f8df7b59b32ecbece037b
        name: my-nodejs
        resources: {}
status: {}
